name: Building LCA Collaboration Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LCA Repository
        uses: actions/checkout@v4

      - name: Checkout Search-Wrapper Repo
        uses: actions/checkout@v4
        with:
          repository: GreenDelta/search-wrapper
          path: search-wrapper-repo

      - name: Checkout Olca Modules Repo
        uses: actions/checkout@v4
        with:
          repository: GreenDelta/olca-modules
          path: olca-modules

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build Search Wrapper Project
        run: |
          cd search-wrapper-repo
          mvn clean install -DskipTests

      - name: Build olca-modules Project
        run: |
          cd olca-modules
          mvn clean install -DskipTests

      - name: Build LCA Repo
        run: mvn clean install -DskipTests

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-war
          path: backend/target/collaboration-server-backend-*.war
